[package]
name = "regex_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.27.0"
clap = { version = "4.5.7", features = ["derive"] }
tui-input = "0.8.0"
env_logger = "0.11.3"
log = "0.4.21"
